### PR TITLE
add Kotlin: An Illustrated Guide

### PR DESCRIPTION
**Pull request by zyberzebra**
- **Project Name**: Illustrated Guide to Kotlin
- **Project URL**: https://typealias.com/start/
- **Project Description**: Book for Learning Kotlin
- **Why it should be added to `awesome-kotlin`**: Fun way to learn kotlin
- [x] At least 8 stars (GitHub project)
- [x] Updated **contents.json** instead of README
- [x] Lib is fully open sourced, written in Kotlin and not a wrapper over compiled lib
- [x] Description does not say "written in Kotlin" or variant 🤓

### CODE REVIEW

**Comment by zyberzebra** [comment]
@matteocrippa @seljabali Can we merge this?

**Comment by sami-eljabali** [comment]
Hi @zyberzebra, I don't maintain this repo nor think it's active; tried [merging](https://github.com/matteocrippa/awesome-kotlin/pull/2) a while back. 

I suggest pushing to https://github.com/KotlinBy/awesome-kotlin & https://github.com/mcxiaoke/awesome-kotlin.

Best!

**Comment by zyberzebra** [comment]
> Hi @zyberzebra, I don't maintain this repo nor think it's active; tried [merging](https://github.com/matteocrippa/awesome-kotlin/pull/2) a while back.
> 
> I suggest pushing to https://github.com/KotlinBy/awesome-kotlin & https://github.com/mcxiaoke/awesome-kotlin.
> 
> Best!

Thanks! I did that:
https://github.com/mcxiaoke/awesome-kotlin/pull/121
https://github.com/KotlinBy/awesome-kotlin/pull/899

**Comment by matteocrippa** [comment]
Sadly this awesome repo didn't work that great as other and it's a bit stuck till 2018, so good you managed to find alternatives

**Pull request closed without merging**
